Repository SupercarMarket/supercarmarket.co.kr, pull requests merged in 2022-11, with the labels that each got.

#15 매장 페이지 필터링 기능
  src/assets/svg/arrow-bottom.svg
  src/assets/svg/close.svg
  src/assets/svg/refresh.svg
  src/components/common/select/index.ts
  src/components/common/select/select.stories.tsx
  src/components/common/select/select.styled.ts
  src/components/common/select/select.tsx
  src/components/market/market-car-kind/index.ts
  src/components/market/market-car-kind/market-car-kind.stories.tsx
  src/components/market/market-car-kind/market-car-kind.styled.ts
  src/components/market/market-car-kind/market-car-kind.tsx
  src/components/market/market-filter/index.ts
  src/components/market/market-filter/market-filter.stories.tsx
  src/components/market/market-filter/market-filter.styled.ts
  src/components/market/market-filter/market-filter.tsx
  src/components/market/market-select/index.ts
  src/components/market/market-select/market-select.stories.tsx
  src/components/market/market-select/market-select.styled.ts
  src/components/market/market-select/market-select.tsx
  src/constants/market.ts
  src/pages/market/[kind].tsx
  src/styles/globalStyles.ts
  src/types/market.ts
Labels: enhancement

#18 feat: 메인 페이지 매거진 리스트 구현
  mocks/handlers.ts
  src/components/common/title/title.tsx
  src/components/home/magazine/index.ts
  src/components/home/magazine/magazine.style.ts
  src/components/home/magazine/magazine.tsx
  src/components/magazine/magazineList/magazineCard.tsx
  src/pages/index.tsx
Labels: enhancement, blan19

#19 feat: Add Home/Market-Community Components
  .env.development
  .env.production
  mocks/handlers.ts
  package.json
  src/components/common/card/card.styled.ts
  src/components/common/card/communityCard.tsx
  src/components/common/card/index.ts
  src/components/common/card/marketCard.tsx
  src/components/home/community/community.styled.ts
  src/components/home/community/community.tsx
  src/components/home/community/index.ts
  src/components/home/magazine/magazine.tsx
  src/components/home/market/index.ts
  src/components/home/market/market.styled.ts
  src/components/home/market/marketBest.tsx
  src/components/home/market/marketNew.tsx
  src/components/home/routerButton/index.ts
  src/components/home/routerButton/routerButton.tsx
  src/components/layout/navbar/navbarItem.tsx
  src/constants/queries.ts
  src/hooks/queries/useCommunityBest.ts
  src/hooks/queries/useMarket.ts
  src/pages/api/community/best.ts
  src/pages/api/market.ts
  src/pages/index.tsx
  src/types/community.ts
  src/types/market.ts
  src/utils/api/community/best.ts
  src/utils/api/fetcher.ts
  src/utils/api/market.ts
Labels: enhancement, blan19

#21 feat: 서버 API 와 Home 연동
  next.config.js
  src/components/common/card/communityCard.tsx
  src/constants/queries.ts
  src/hooks/queries/home/userHomeMagazine.ts
  src/pages/api/home.ts
  src/pages/index.tsx
  src/types/community.ts
  src/utils/api/community/best.ts
  src/utils/api/home.ts
Labels: enhancement, blan19

#23 Hotfix: build error #22
  src/pages/index.tsx
  src/utils/api/magazine.ts
  src/utils/api/market.ts
Labels: blan19, 버그, 핫픽스

#20 매물 페이지 리스트 구현
  mocks/handlers.ts
  src/assets/svg/menu.svg
  src/assets/svg/sqaure.svg
  src/components/common/card/marketCard.tsx
  src/components/common/select/select.styled.ts
  src/components/common/select/select.tsx
  src/components/market/market-banner/index.ts
  src/components/market/market-banner/market-banner.styled.ts
  src/components/market/market-banner/market-banner.tsx
  src/components/market/market-car-category/index.ts
  src/components/market/market-car-category/market-car-category.stories.tsx
  src/components/market/market-car-category/market-car-category.styled.ts
  src/components/market/market-car-category/market-car-category.tsx
  src/components/market/market-car-kind/index.ts
  src/components/market/market-card/index.ts
  src/components/market/market-card/market-card.styled.ts
  src/components/market/market-card/market-card.tsx
  src/components/market/market-filter/market-filter.stories.tsx
  src/components/market/market-filter/market-filter.styled.ts
  src/components/market/market-filter/market-filter.tsx
  src/components/market/market-list/index.ts
  src/components/market/market-list/market-list.styled.ts
  src/components/market/market-list/market-list.tsx
  src/components/market/market-row/index.ts
  src/components/market/market-row/market-row.styled.ts
  src/components/market/market-row/market-row.tsx
  src/components/market/market-select/market-select.tsx
  src/constants/market.ts
  src/constants/queries.ts
  src/hooks/market/useMarketFilter.ts
  src/hooks/queries/useMarket.ts
  src/pages/index.tsx
  src/pages/market/[category].tsx
  src/pages/market/[kind].tsx
  src/types/market.ts
  src/utils/api/magazine.ts
  src/utils/api/market.ts
  src/utils/market/makeMarketQuery.ts
  src/utils/market/market-list.ts
Labels: enhancement

#27 feat: Comment Component Mark up
  next.config.js
  package.json
  src/assets/svg/chat.svg
  src/components/common/card/communityCard.tsx
  src/components/common/comment/comment.styled.ts
  src/components/common/comment/comment.tsx
  src/components/common/comment/commentArea.tsx
  src/components/common/comment/commentBody.tsx
  src/components/common/comment/commentHead.tsx
  src/components/common/comment/index.ts
  src/components/common/container/container.tsx
  src/components/common/pagination/pagination.tsx
  src/hooks/queries/home/useHome.ts
  src/pages/index.tsx
  src/pages/magazine/[id].tsx
  src/pages/magazine/index.tsx
  src/styles/responsive.ts
  src/types/comment.ts
  src/types/community.ts
  src/utils/api/fetcher.ts
  src/utils/api/home.ts
  src/utils/api/magazine.ts
  src/utils/api/market.ts
  src/utils/error.ts
Labels: enhancement, blan19
