Repository SupercarMarket/supercarmarket.co.kr, pull requests merged in 2023-06, with the labels that each got.

#182 fix. terms 변경(서비스 약관, 개인정보 약관)
  apps/web/src/components/common/modal/termModal.tsx
  apps/web/src/constants/terms.ts
  apps/web/src/constants/termsPrivate.ts
  apps/web/src/constants/termsService.ts
Labels: 📝 docs

#183 fix: 최종 qa 리스트 수정
  apps/web/src/components/auth/findIdForm/findIdForm.tsx
  apps/web/src/components/common/comment/components/commentBody.tsx
  apps/web/src/components/layout/footer/footer.styled.ts
  apps/web/src/components/layout/footer/footer.tsx
  apps/web/src/components/layout/layout.tsx
  apps/web/src/components/market/marketDetail/components/marketMine/marketMine.tsx
Labels: 🐛 bug, ❗️ changes requested

#188 방송 관련 loading 네이밍 변경
  apps/web/src/components/live/Publisher.tsx
  apps/web/src/components/live/Subscriber.tsx
  apps/web/src/components/live/modal/Loader.tsx
Labels: 🐛 bug

#187 fix: 방송 관련 핸들링 추가
  apps/web/public/css/live.module.css
  apps/web/src/components/live/ChatInfo.tsx
  apps/web/src/components/live/Publisher.tsx
  apps/web/src/components/live/Subscriber.tsx
  apps/web/src/components/live/modal/Loader.tsx
  apps/web/src/components/live/modal/index.tsx
  apps/web/src/http/server/live/apis.ts
  apps/web/src/pages/_app.tsx
  apps/web/src/pages/live/Create.tsx
  apps/web/src/pages/live/index.tsx
Labels: hotfix

#193 fix. 매거진 따끈따끈한 최식소식의 매거진 클릭 시 상세 페이지 Link 추가
  apps/web/src/components/magazine/magazineList/magazineList.tsx
Labels: ⛏refactoring

#194 bugFix. 제휴 업체 이미지 사이즈 변경
  apps/web/src/components/home/partnership/partnership.tsx
Labels: 🐛 bug

#195 feat: 최종 Qa 리스트업 수정
  apps/web/public/images/appstore.png
  apps/web/public/images/appstore_1.png
  apps/web/public/images/appstore_2.png
  apps/web/public/images/appstore_3.png
  apps/web/public/images/appstore_4.png
  apps/web/public/images/playstore.png
  apps/web/src/components/account/accountPasswordForm/accountPasswordForm.tsx
  apps/web/src/components/common/modal/appStoreModal.tsx
  apps/web/src/components/home/partnership/partnership.tsx
  apps/web/src/components/layout/footer/footer.styled.ts
  apps/web/src/components/layout/footer/footer.tsx
  apps/web/src/components/magazine/magazineList/magazineList.tsx
  apps/web/src/constants/form/dealer.ts
Labels: 🐛 bug, ❗️ changes requested

#196 fix: 최종 QA 리스트업 수정
  apps/web/package.json
  apps/web/src/components/account/accountCategoryList/accountCategoryList.tsx
  apps/web/src/components/market/marketContents/marketContents.tsx
  apps/web/src/components/market/marketDetail/components/marketDetailCarousel/marketDetailCarousel.tsx
  apps/web/src/components/market/marketDetail/components/marketMine/marketMine.tsx
  apps/web/src/http/server/market/apis.ts
  apps/web/src/http/server/market/mutations.ts
  pnpm-lock.yaml
Labels: 🐛 bug, ❗️ changes requested

#197 release(web): v1.0.6
  apps/web/package.json
  apps/web/src/components/account/accountCategoryList/accountCategoryList.tsx
  apps/web/src/components/market/marketContents/marketContents.tsx
  apps/web/src/components/market/marketDetail/components/marketDetailCarousel/marketDetailCarousel.tsx
  apps/web/src/components/market/marketDetail/components/marketMine/marketMine.tsx
  apps/web/src/http/server/market/apis.ts
  apps/web/src/http/server/market/mutations.ts
  pnpm-lock.yaml
Labels: 🐛 bug, ❗️ changes requested
