Repository SupercarMarket/supercarmarket.co.kr, pull requests merged in 2023-04, with the labels that each got.

#130 refactor(web): Auth/Inquiry 컴포넌트 내부에 독립적으로 존재하던 Api를 tanstack-query로 통일
  apps/web/src/components/account/accountPasswordForm/accountPasswordForm.tsx
  apps/web/src/components/account/accountUpdateForm/accountUpdateForm.tsx
  apps/web/src/components/auth/authFormItem/authFormItem.tsx
  apps/web/src/components/auth/findForm/findForm.tsx
  apps/web/src/components/auth/findForm/index.ts
  apps/web/src/components/auth/findIdForm/findIdForm.tsx
  apps/web/src/components/auth/findIdForm/index.ts
  apps/web/src/components/auth/findPasswordForm/findPasswordForm.tsx
  apps/web/src/components/auth/findPasswordForm/index.ts
  apps/web/src/components/auth/index.ts
  apps/web/src/components/auth/phoneForm/phoneForm.tsx
  apps/web/src/components/auth/resultId/resultId.tsx
  apps/web/src/components/auth/signinForm/signinForm.tsx
  apps/web/src/components/auth/signupForm/signupForm.tsx
  apps/web/src/components/inquiry/advertisementForm/advertisementForm.tsx
  apps/web/src/components/inquiry/dealerForm/dealerForm.tsx
  apps/web/src/components/inquiry/miscForm/miscForm.tsx
  apps/web/src/components/inquiry/partnershipForm/partnershipForm.tsx
  apps/web/src/components/inquiry/saleForm/saleForm.tsx
  apps/web/src/constants/form/signup.ts
  apps/web/src/hooks/useAuth.ts
  apps/web/src/http/server/auth/apis.ts
  apps/web/src/http/server/auth/index.ts
  apps/web/src/http/server/auth/keys.ts
  apps/web/src/http/server/auth/mutation.ts
  apps/web/src/http/server/auth/token.ts
  apps/web/src/http/server/auth/user.ts
  apps/web/src/http/server/inquiry/apis.ts
  apps/web/src/http/server/inquiry/index.ts
  apps/web/src/http/server/inquiry/keys.ts
  apps/web/src/http/server/inquiry/mutations.ts
  apps/web/src/http/server/next/getSession.ts
  apps/web/src/http/server/next/index.ts
  apps/web/src/pages/account/[sub]/index.tsx
  apps/web/src/pages/account/[sub]/update-password.tsx
  apps/web/src/pages/account/[sub]/update.tsx
  apps/web/src/pages/api/auth/[...nextauth].ts
  apps/web/src/pages/api/auth/user/oauth.ts
  apps/web/src/pages/auth/find-id.tsx
  apps/web/src/pages/auth/find-password.tsx
  apps/web/src/pages/auth/find-result-id.tsx
  apps/web/src/pages/auth/find/index.tsx
  apps/web/src/pages/community/[subject]/[category]/[id]/index.tsx
  apps/web/src/pages/community/[subject]/[category]/[id]/update.tsx
  apps/web/src/pages/community/create.tsx
  apps/web/src/pages/inquiry/market.tsx
  apps/web/src/pages/magazine/[id].tsx
  apps/web/src/pages/market/[category]/[id].tsx
  apps/web/src/utils/misc.ts
  packages/lib/api/fetcherWrapper.ts
Labels: ⛏refactoring

#131 feat(web): 배너 SSR 삭제 / 너비 100% 적용
  apps/web/src/components/home/banner/banner.tsx
  apps/web/src/components/layout/footer/footer.styled.ts
  apps/web/src/components/layout/layout.styled.ts
  apps/web/src/pages/_document.tsx
  apps/web/src/pages/index.tsx
  apps/web/src/styles/mediaQuery.ts
  apps/web/src/styles/responsive.ts
  packages/lib/index.ts
  packages/lib/link.ts
  packages/ui/styles/mediaQuery.ts
  packages/ui/styles/responsive.ts
Labels: ✨ feature

#132 fix(web): 찜하기 기능 수정
  apps/web/src/components/market/marketContents/marketContents.tsx
  apps/web/src/components/market/marketDetail/components/marketLike/marketLike.tsx
  apps/web/src/components/market/marketDetail/marketDetail.tsx
  apps/web/src/http/server/market/apis.ts
  apps/web/src/http/server/market/mutations.ts
  apps/web/src/http/server/market/queries.ts
  apps/web/src/pages/market/[category]/[id].tsx
Labels: 🐛 bug

#135 fix(web): 모바일 QA 리스트 피드백 반영 (매물)
  apps/web/src/components/common/carousel/carousel.styled.ts
  apps/web/src/components/common/carousel/carousel.tsx
  apps/web/src/components/common/select/select.tsx
  apps/web/src/components/market/marketCar/marketCar.tsx
  apps/web/src/components/market/marketCard/marketCard.tsx
  apps/web/src/components/market/marketDetail/components/marketDetailCarousel/marketDetailCarousel.styled.ts
  apps/web/src/components/market/marketDetail/components/marketDetailCarousel/marketDetailCarousel.tsx
  apps/web/src/components/market/marketFilter/marketFilterArea/marketFilterArea.tsx
  apps/web/src/components/market/marketList/marketList.tsx
  apps/web/src/components/market/marketRow/marketRow.tsx
  apps/web/src/components/partnership/partnershipCard/partnershipCard.tsx
  apps/web/src/components/partnership/partnershipDetail/partnershipDetail.tsx
  apps/web/src/components/partnership/partnershipDetailCard/partnershipDetailCard.tsx
  apps/web/src/hooks/useSearchKeyword.ts
  packages/types/partnership.d.ts
Labels: 🐛 bug, ❗️ changes requested

#136 feat(web): PWA 적용
  apps/web/.gitignore
  apps/web/next.config.js
  apps/web/package.json
  apps/web/public/images/logo/site.webmanifest
  apps/web/public/manifest.json
  apps/web/public/pwa/icon-128x128.png
  apps/web/public/pwa/icon-144x144.png
  apps/web/public/pwa/icon-152x152.png
  apps/web/public/pwa/icon-192x192.png
  apps/web/public/pwa/icon-384x384.png
  apps/web/public/pwa/icon-48x48.png
  apps/web/public/pwa/icon-512x512.png
  apps/web/public/pwa/icon-72x72.png
  apps/web/public/pwa/icon-96x96.png
  apps/web/src/http/server/next/image.ts
  apps/web/src/pages/_document.tsx
  pnpm-lock.yaml
Labels: ✨ feature

#137 fix(web): pwa 이미지 아이콘 사이즈/경로 변경
  apps/web/public/manifest.json
  apps/web/public/pwa/android-icon-144x144.png
  apps/web/public/pwa/android-icon-192x192.png
  apps/web/public/pwa/android-icon-36x36.png
  apps/web/public/pwa/android-icon-384x384.png
  apps/web/public/pwa/android-icon-48x48.png
  apps/web/public/pwa/android-icon-512x512.png
  apps/web/public/pwa/android-icon-72x72.png
  apps/web/public/pwa/android-icon-96x96.png
  apps/web/public/pwa/apple-icon-114x114.png
  apps/web/public/pwa/apple-icon-120x120.png
  apps/web/public/pwa/apple-icon-144x144.png
  apps/web/public/pwa/apple-icon-152x152.png
  apps/web/public/pwa/apple-icon-180x180.png
  apps/web/public/pwa/apple-icon-57x57.png
  apps/web/public/pwa/apple-icon-60x60.png
  apps/web/public/pwa/apple-icon-72x72.png
  apps/web/public/pwa/apple-icon-76x76.png
  apps/web/public/pwa/apple-icon-precomposed.png
  apps/web/public/pwa/apple-icon.png
  apps/web/public/pwa/icon-128x128.png
  apps/web/public/pwa/icon-144x144.png
  apps/web/public/pwa/icon-152x152.png
  apps/web/public/pwa/icon-192x192.png
  apps/web/public/pwa/icon-48x48.png
  apps/web/public/pwa/icon-72x72.png
  apps/web/public/pwa/icon-96x96.png
  apps/web/public/pwa/ms-icon-144x144.png
  apps/web/public/pwa/ms-icon-150x150.png
  apps/web/public/pwa/ms-icon-310x310.png
  apps/web/public/pwa/ms-icon-70x70.png
  apps/web/src/pages/_document.tsx
Labels: ❗️ changes requested

#138 fix(web): Google OAuth 콜백 에러 / 모바일 QA 레이아웃 문제 수정
  apps/web/src/components/account/accountCategoryList/accountCategoryList.tsx
  apps/web/src/components/common/posting/posting.tsx
  apps/web/src/components/community/communityBestList/communityBestList.tsx
  apps/web/src/components/community/communityCard/communityCard.tsx
  apps/web/src/components/home/banner/banner.tsx
  apps/web/src/components/home/community/community.tsx
  apps/web/src/components/home/magazine/magazine.tsx
  apps/web/src/components/home/market/marketBest.tsx
  apps/web/src/components/home/market/marketNew.tsx
  apps/web/src/components/inquiry/inquiryCard/inquiryCard.tsx
  apps/web/src/http/server/home/apis.ts
  apps/web/src/http/server/home/queries.ts
  apps/web/src/middleware.ts
  apps/web/src/pages/_app.tsx
  apps/web/src/pages/account/[sub]/index.tsx
  apps/web/src/pages/api/auth/[...nextauth].ts
  apps/web/src/pages/index.tsx
  apps/web/src/utils/misc.ts
  packages/types/community.d.ts
  packages/ui/components/attachedFile/attachedFile.tsx
  packages/ui/components/attachedFile/index.ts
  packages/ui/components/index.ts
  packages/ui/index.tsx
  packages/ui/package.json
  pnpm-lock.yaml
Labels: 🐛 bug, ❗️ changes requested

#142 fix(web): 디바이스가 갤럭시인 경우 나오는 통합검색 포커싱 에러 / 메인 제휴업체 미적용
  apps/web/src/components/auth/phoneForm/phoneForm.tsx
  apps/web/src/components/common/advertisement/advertisement.tsx
  apps/web/src/components/common/announcement/announcement.tsx
  apps/web/src/components/common/announcement/index.ts
  apps/web/src/components/common/comment/components/commentBody.tsx
  apps/web/src/components/common/modal/modal.tsx
  apps/web/src/components/common/modal/termModal.tsx
  apps/web/src/components/home/partnership/components/index.ts
  apps/web/src/components/home/partnership/components/partnershipArrow.tsx
  apps/web/src/components/home/partnership/index.ts
  apps/web/src/components/home/partnership/partnership.tsx
  apps/web/src/components/inquiry/inquiryFormItem/inquiryFormItem.tsx
  apps/web/src/components/inquiry/saleForm/saleForm.tsx
  apps/web/src/components/magazine/magazineScrape/magazineScrape.tsx
  apps/web/src/components/market/marketBanner/index.ts
  apps/web/src/components/partnership/banner/banner.tsx
  apps/web/src/components/partnership/banner/index.ts
  apps/web/src/constants/form/index.ts
  apps/web/src/constants/form/partnership.ts
  apps/web/src/http/server/account/apis.ts
  apps/web/src/pages/index.tsx
  apps/web/src/pages/market/index.tsx
  apps/web/src/pages/partnership/index.tsx
  apps/web/src/styles/globalStyles.ts
  packages/ui/components/searchbar/searchbar.tsx
  packages/ui/form/form.styled.ts
  packages/ui/form/formInput.tsx
  packages/ui/form/formSelect.tsx
Labels: 🐛 bug, ❗️ changes requested

#143 refactor(web): Web Optimization
  apps/web/src/components/common/logo/logo.tsx
  apps/web/src/components/home/partnership/partnership.tsx
  apps/web/src/pages/_app.tsx
  packages/hooks/index.ts
  packages/hooks/useBooleanState.ts
  packages/hooks/useIntersectionObserver.ts
  packages/ui/components/title/title.tsx
Labels: ⛏refactoring

#146 feat(web): 404 / 500 페이지 구현
  apps/web/public/images/404.png
  apps/web/public/images/500.png
  apps/web/src/components/account/accountCategoryList/accountCategoryList.tsx
  apps/web/src/components/account/accountPasswordForm/accountPasswordForm.tsx
  apps/web/src/components/account/accountUpdateForm/accountUpdateForm.tsx
  apps/web/src/components/layout/authLayout.tsx
  apps/web/src/components/layout/layout.tsx
  apps/web/src/components/market/marketDetail/components/marketMine/marketMine.tsx
  apps/web/src/http/server/market/mutations.ts
  apps/web/src/pages/404.tsx
  apps/web/src/pages/500.tsx
  apps/web/src/pages/_app.tsx
  apps/web/src/pages/account/[sub]/update-password.tsx
  apps/web/src/pages/account/[sub]/update.tsx
  apps/web/src/pages/auth/find-id.tsx
  apps/web/src/pages/auth/find-password.tsx
  apps/web/src/pages/auth/phone.tsx
  apps/web/src/pages/auth/signin.tsx
  apps/web/src/pages/auth/signup.tsx
Labels: ✨ feature

#147 feat(web): 광고 Api 적용
  apps/web/src/components/account/accountCategoryList/accountCategoryList.tsx
  apps/web/src/components/auth/signinForm/signinForm.tsx
  apps/web/src/components/common/advertisement/advertisement.tsx
  apps/web/src/components/common/advertisement/index.ts
  apps/web/src/components/common/advertisements/advertisements.tsx
  apps/web/src/components/common/advertisements/components/advertisement.tsx
  apps/web/src/components/common/advertisements/components/banner.tsx
  apps/web/src/components/common/advertisements/index.ts
  apps/web/src/components/home/banner/index.ts
  apps/web/src/components/layout/layout.tsx
  apps/web/src/http/server/home/apis.ts
  apps/web/src/http/server/home/keys.ts
  apps/web/src/http/server/home/queries.ts
  apps/web/src/pages/api/auth/[...nextauth].ts
  apps/web/src/pages/community/[subject]/[category]/[id]/index.tsx
  apps/web/src/pages/community/[subject]/[category]/[id]/update.tsx
  apps/web/src/pages/community/[subject]/index.tsx
  apps/web/src/pages/community/create.tsx
  apps/web/src/pages/index.tsx
  apps/web/src/pages/inquiry/index.tsx
  apps/web/src/pages/magazine/[id].tsx
  apps/web/src/pages/magazine/index.tsx
  apps/web/src/pages/market/[category]/[id].tsx
  apps/web/src/pages/market/index.tsx
  apps/web/src/pages/partnership/[category]/[id].tsx
  apps/web/src/pages/partnership/index.tsx
  apps/web/src/types/ads.d.ts
  packages/lib/formatter.ts
Labels: ✨ feature

#148 fix(web,ui): 추가적으로 올라온 QA 리스트 피드백
  apps/web/src/components/auth/signinForm/signinForm.tsx
  apps/web/src/components/common/advertisements/components/advertisement.tsx
  apps/web/src/components/common/comment/comment.tsx
  apps/web/src/components/common/posting/posting.tsx
  apps/web/src/components/inquiry/inquiryNavbar/inquiryNavbar.tsx
  apps/web/src/components/magazine/magazineBanner/magazineBanner.tsx
  apps/web/src/components/magazine/magazineCard/magazineCard.tsx
  apps/web/src/components/magazine/magazineDealer/magazineDealer.tsx
  apps/web/src/components/market/marketContents/marketContents.tsx
  apps/web/src/components/partnership/partnershipContents/partnershipContents.tsx
  apps/web/src/components/partnership/partnershipDetail/partnershipDetail.tsx
  apps/web/src/http/server/auth/apis.ts
  apps/web/src/http/server/magazine/queries.ts
  apps/web/src/pages/api/auth/[...nextauth].ts
  apps/web/src/pages/magazine/[id].tsx
  packages/hooks/useUrlQuery.ts
  packages/lib/formatter.ts
  packages/ui/components/divider/divider.tsx
  packages/ui/components/pagination/pagination.tsx
Labels: 🐛 bug, ❗️ changes requested

#150 fix(web): 추가적으로 올라온 QA 리스트 피드백
  apps/web/src/components/account/accountUpdateForm/accountUpdateForm.tsx
  apps/web/src/components/auth/authFormItem/authFormItem.tsx
  apps/web/src/components/auth/findIdForm/findIdForm.tsx
  apps/web/src/components/auth/findPasswordForm/findPasswordForm.tsx
  apps/web/src/components/auth/phoneForm/phoneForm.tsx
  apps/web/src/components/auth/signupForm/signupForm.tsx
  apps/web/src/components/common/advertisements/advertisements.tsx
  apps/web/src/feature/DeviceProvider/deviceProvider.tsx
  apps/web/src/middleware.ts
Labels: 🐛 bug, ❗️ changes requested

#151 refactor(web): 기존 패키지 타입들을 web 패키지 내부 모듈로 이관
  apps/web/src/components/account/accountCategoryList/accountCategoryList.tsx
  apps/web/src/components/common/advertisements/advertisements.tsx
  apps/web/src/components/common/advertisements/components/advertisement.tsx
  apps/web/src/feature/DeviceProvider/deviceContext.ts
  apps/web/src/feature/DeviceProvider/deviceProvider.tsx
  apps/web/src/feature/DeviceProvider/index.ts
  apps/web/src/feature/index.ts
  apps/web/src/hooks/useDevice.ts
  apps/web/src/http/server/home/queries.ts
  apps/web/src/pages/404.tsx
  apps/web/src/pages/500.tsx
  apps/web/src/pages/_app.tsx
  apps/web/src/types/account.d.ts
  apps/web/src/types/ads.d.ts
  apps/web/src/types/auth.d.ts
  apps/web/src/types/comment.d.ts
  apps/web/src/types/community.d.ts
  apps/web/src/types/index.d.ts
  apps/web/src/types/inquiry.d.ts
  apps/web/src/types/magazine.d.ts
  apps/web/src/types/market.d.ts
  apps/web/src/types/partnership.d.ts
  apps/web/src/types/search.d.ts
Labels: ⛏refactoring

#152 fix(web): 매물 등록 / 커뮤니티 게시글 등록 SSR -> CSR
  apps/web/src/components/common/advertisements/advertisements.tsx
  apps/web/src/components/community/communityForm/communityCreate.tsx
  apps/web/src/components/community/communityForm/components/communityEditor.tsx
  apps/web/src/components/community/communityForm/components/communityForm.tsx
  apps/web/src/components/community/communityForm/index.ts
  apps/web/src/components/community/index.ts
  apps/web/src/components/fallback/loading.tsx
  apps/web/src/components/inquiry/saleForm/saleForm.tsx
  apps/web/src/http/server/account/queries.ts
  apps/web/src/http/server/community/keys.ts
  apps/web/src/http/server/community/queries.ts
  apps/web/src/pages/community/create.tsx
  apps/web/src/pages/inquiry/market.tsx
  apps/web/src/types/account.d.ts
Labels: 🐛 bug

#160 refactor(web): OAuth2 플로우
  apps/web/src/http/server/auth/apis.ts
  apps/web/src/pages/api/auth/[...nextauth].ts
  apps/web/src/types/next-auth.d.ts
Labels: ⛏refactoring

#161 release: v1.0.1
  apps/web/src/http/server/auth/apis.ts
  apps/web/src/pages/api/auth/[...nextauth].ts
  apps/web/src/types/next-auth.d.ts
Labels: ⛏refactoring

#162 hotfix(web): OAuth Redirect Url Error
  apps/web/src/http/server/auth/apis.ts
  apps/web/src/pages/api/auth/[...nextauth].ts
Labels: hotfix

#163 fix(web): 새로 올라온 QA 리스트 - 1
  apps/web/src/components/account/profile/components/profileRepresentative.tsx
  apps/web/src/components/community/communityCard/communityCard.tsx
  apps/web/src/components/home/community/community.tsx
  apps/web/src/components/home/magazine/magazine.tsx
  apps/web/src/components/home/market/marketNew.tsx
  apps/web/src/components/home/partnership/partnership.tsx
  apps/web/src/components/home/routerButton/routerButton.tsx
  apps/web/src/components/magazine/magazineCard/magazineCard.tsx
  apps/web/src/constants/core.ts
  apps/web/src/pages/index.tsx
  packages/ui/components/searchbar/searchbar.tsx
Labels: 🐛 bug, ❗️ changes requested

#164 release(web): 전체적인 UI 관련 버그를 개선했습니다.
  apps/web/src/components/account/profile/components/profileRepresentative.tsx
  apps/web/src/components/community/communityCard/communityCard.tsx
  apps/web/src/components/home/community/community.tsx
  apps/web/src/components/home/magazine/magazine.tsx
  apps/web/src/components/home/market/marketNew.tsx
  apps/web/src/components/home/partnership/partnership.tsx
  apps/web/src/components/home/routerButton/routerButton.tsx
  apps/web/src/components/magazine/magazineCard/magazineCard.tsx
  apps/web/src/constants/core.ts
  apps/web/src/pages/index.tsx
  packages/ui/components/searchbar/searchbar.tsx
Labels: ✨ feature

#165 feat(web): WebRTC을 사용한 라이브 페이지 초기 구현
  apps/web/next.config.js
  apps/web/package.json
  apps/web/public/css/live.module.css
  apps/web/public/images/live/icons/CameraCloseIcon.svg
  apps/web/public/images/live/icons/LockerIcon.svg
  apps/web/public/images/live/icons/SubscriberIcon.svg
  apps/web/public/images/live/icons/TagCloseBtn.svg
  apps/web/public/images/live/icons/VolumeIcon.svg
  apps/web/src/components/live/ChatInfo.tsx
  apps/web/src/components/live/Publisher.tsx
  apps/web/src/components/live/Subscriber.tsx
  apps/web/src/components/live/modal/index.tsx
  apps/web/src/constants/form/live.ts
  apps/web/src/http/core/index.ts
  apps/web/src/http/server/live/apis.ts
  apps/web/src/http/server/live/index.ts
  apps/web/src/http/server/live/keys.ts
  apps/web/src/http/server/live/mutaitons.ts
  apps/web/src/http/server/live/queries.ts
  apps/web/src/pages/live/Create.tsx
  apps/web/src/pages/live/[Channel].tsx
  apps/web/src/pages/live/index.tsx
  apps/web/src/types/env.d.ts
  apps/web/src/types/live.d.ts
  package.json
  packages/ui/form/formAttachment.tsx
  packages/ui/form/formLabel.tsx
  pnpm-lock.yaml
  turbo.json
Labels: ✨ feature
