Repository SupercarMarket/supercarmarket.co.kr, pull requests merged in 2023-03, with the labels that each got.

#74 feat: Community 게시글 등록/수정 기능 구현
  apps/web/src/components/common/modal/temporaryStorageModal.tsx
  apps/web/src/components/common/posting/posting.tsx
  apps/web/src/components/community/communityCard/communityCard.tsx
  apps/web/src/components/community/communityForm/communityEditor.tsx
  apps/web/src/components/community/communityForm/communityForm.tsx
  apps/web/src/components/community/communityList/communityList.tsx
  apps/web/src/constants/community.ts
  apps/web/src/hooks/mutations/community/useAddCommunityTemporaryStorage.ts
  apps/web/src/hooks/queries/community/useCommunity.ts
  apps/web/src/pages/community/[subject]/[category]/[id]/index.tsx
  apps/web/src/pages/community/[subject]/[category]/[id]/update.tsx
  apps/web/src/pages/community/create.tsx
  packages/lib/index.ts
  packages/lib/random.ts
  packages/types/community.d.ts
  packages/ui/components/searchbar/searchbar.tsx
  packages/ui/form/formFiles.tsx
  packages/ui/form/formSelect.tsx
Labels: enhancement, blan19

#75 refactor: Tab Component 관련 중복 코드 재사용
  apps/web/public/images/logo.png
  apps/web/src/components/common/logo/index.ts
  apps/web/src/components/common/logo/logo.tsx
  apps/web/src/components/common/posting/posting.tsx
  apps/web/src/components/community/communityCard/communityCard.tsx
  apps/web/src/components/community/communityForm/communityForm.tsx
  apps/web/src/components/community/communityList/communityList.tsx
  apps/web/src/components/layout/header/header.tsx
  apps/web/src/hooks/mutations/community/useRemoveCommunityPost.ts
  apps/web/src/pages/community/[subject]/[category]/[id]/update.tsx
  apps/web/src/pages/community/[subject]/index.tsx
  apps/web/src/pages/market/detail/[id].tsx
  packages/ui/components/index.ts
  packages/ui/components/logo/logo.tsx
  packages/ui/components/tab/tab.tsx
  packages/ui/index.tsx
Labels: enhancement, blan19

#76 refactor: Market Detail 페이지 렌더링 속도 개선
  .github/workflows/chromatic.yml
  apps/web/package.json
  apps/web/src/components/fallback/loading.tsx
  apps/web/src/components/market/marketCard/marketCard.tsx
  apps/web/src/components/market/marketContents/marketContents.tsx
  apps/web/src/components/market/marketDetail/components/marketDetailCarousel/marketDetailCarousel.tsx
  apps/web/src/components/market/marketDetail/marketDetail.tsx
  apps/web/src/hooks/queries/useBase64.ts
  apps/web/src/hooks/queries/useMarketDetail.ts
  apps/web/src/pages/api/image/base64.ts
  apps/web/src/pages/market/[category]/[id].tsx
  apps/web/src/pages/market/[category]/index.tsx
  apps/web/src/utils/api/image.ts
  packages/types/market.d.ts
  pnpm-lock.yaml
Labels: enhancement, blan19

#80 fix: OAuth2 로그인 오류 수정
  apps/web/src/components/account/accountCategory/accountCategory.tsx
  apps/web/src/components/account/accountNavbar/accountNavbar.tsx
  apps/web/src/components/account/accountNavbar/index.ts
  apps/web/src/components/account/index.ts
  apps/web/src/components/auth/phoneForm/phoneForm.tsx
  apps/web/src/components/auth/signinForm/signinForm.tsx
  apps/web/src/components/market/marketBanner/marketBanner.tsx
  apps/web/src/components/market/marketCarKind/index.ts
  apps/web/src/components/market/marketCarKind/marketCarKind.styled.ts
  apps/web/src/components/market/marketCarKind/marketCarKind.tsx
  apps/web/src/components/partnership/category/category.styled.ts
  apps/web/src/components/partnership/category/category.tsx
  apps/web/src/components/partnership/category/index.ts
  apps/web/src/constants/account.ts
  apps/web/src/constants/market.ts
  apps/web/src/constants/partnership.ts
  apps/web/src/pages/account/[sub]/index.tsx
  apps/web/src/pages/api/auth/[...nextauth].ts
  apps/web/src/pages/market/[category]/index.tsx
  apps/web/src/pages/partnership/[category]/index.tsx
  apps/web/src/utils/api/auth/phone.ts
  packages/ui/components/category/category.tsx
  packages/ui/components/category/index.ts
  packages/ui/components/index.ts
  packages/ui/index.tsx
Labels: enhancement, blan19

#82 refactor: 도메인 구조 통일성있게 변경
  apps/web/src/components/layout/layout.tsx
  apps/web/src/components/market/marketCar/index.ts
  apps/web/src/components/market/marketCar/marketCar.styled.ts
  apps/web/src/components/market/marketCar/marketCar.tsx
  apps/web/src/components/market/marketCarList/index.ts
  apps/web/src/components/market/marketCarList/marketCarList.tsx
  apps/web/src/components/market/marketCard/marketCard.tsx
  apps/web/src/components/market/marketList/index.ts
  apps/web/src/components/market/marketList/marketList.tsx
  apps/web/src/constants/partnership.ts
  apps/web/src/hooks/queries/useMarket.ts
  apps/web/src/pages/market/index.tsx
  apps/web/src/pages/partnership/index.tsx
  packages/ui/components/tab/tab.tsx
Labels: ⛏refactoring

#83 refacor: 마이페이지 라우팅 보안 강화 & 모바일 레이아웃 접근성 향상
  apps/web/src/components/auth/authFormItem/authFormItem.tsx
  apps/web/src/components/common/avatar/avatar.tsx
  apps/web/src/components/common/comment/commentBody.tsx
  apps/web/src/components/common/logo/logo.tsx
  apps/web/src/components/common/posting/postingHead.tsx
  apps/web/src/components/community/communityCard/communityCard.tsx
  apps/web/src/components/home/community/community.tsx
  apps/web/src/components/home/magazine/magazine.tsx
  apps/web/src/components/home/market/marketBest.tsx
  apps/web/src/components/home/market/marketNew.tsx
  apps/web/src/components/layout/header/header.tsx
  apps/web/src/components/layout/layout.styled.ts
  apps/web/src/components/magazine/magazineBanner/magazineBanner.tsx
  apps/web/src/components/magazine/magazineList/magazineCard.tsx
  apps/web/src/components/magazine/magazineList/magazineList.tsx
  apps/web/src/components/market/marketCar/marketCar.tsx
  apps/web/src/components/market/marketCard/marketCard.tsx
  apps/web/src/components/market/marketList/marketList.tsx
  apps/web/src/components/partnership/banner/banner.styled.ts
  apps/web/src/constants/auth.ts
  apps/web/src/feature/authProvider.tsx
  apps/web/src/pages/account/[sub]/index.tsx
  apps/web/src/pages/api/auth/[...nextauth].ts
  apps/web/src/pages/community/[subject]/[category]/[id]/index.tsx
  apps/web/src/pages/community/[subject]/[category]/[id]/update.tsx
  apps/web/src/pages/community/[subject]/index.tsx
  apps/web/src/pages/community/create.tsx
  apps/web/src/pages/index.tsx
  apps/web/src/pages/inquiry/advertisement.tsx
  apps/web/src/pages/inquiry/dealer.tsx
  apps/web/src/pages/inquiry/index.tsx
  apps/web/src/pages/inquiry/market.tsx
  apps/web/src/pages/inquiry/misc.tsx
  apps/web/src/pages/inquiry/partnership.tsx
  apps/web/src/pages/magazine/[id].tsx
  apps/web/src/pages/magazine/index.tsx
  apps/web/src/pages/market/[category]/[id].tsx
  apps/web/src/pages/market/index.tsx
  apps/web/src/pages/partnership/[category]/[id].tsx
  apps/web/src/pages/partnership/index.tsx
  apps/web/src/pages/search.tsx
  apps/web/src/utils/validator.ts
  packages/types/base.d.ts
  packages/types/community.d.ts
  packages/ui/components/searchbar/searchbar.tsx
  packages/ui/components/tab/tab.tsx
Labels: ⛏refactoring

#85 feat: Account 페이지 회원탈퇴 기능 구현
  apps/web/src/components/account/accountUpdateForm/accountUpdateForm.tsx
  apps/web/src/components/common/modal/modal.tsx
  apps/web/src/components/inquiry/inquiryNavbar/inquiryNavbar.tsx
  apps/web/src/components/layout/accountLayout.tsx
  apps/web/src/components/layout/footer/footer.tsx
  apps/web/src/components/layout/hamburger/hamburger.tsx
  apps/web/src/components/layout/header/header.tsx
  apps/web/src/components/layout/layout.tsx
  apps/web/src/components/layout/navbar/navbar.tsx
  apps/web/src/components/layout/toggle/toggle.tsx
  apps/web/src/pages/_document.tsx
  apps/web/src/pages/account/[sub]/update.tsx
  apps/web/src/pages/index.tsx
  apps/web/src/pages/inquiry/index.tsx
  apps/web/src/types/env.d.ts
  packages/ui/components/alert/alert.tsx
  packages/ui/components/button/button.tsx
  packages/ui/components/category/category.tsx
  packages/ui/components/divider/divider.tsx
  packages/ui/components/highlight/highlight.tsx
  packages/ui/components/searchbar/searchbar.tsx
  packages/ui/components/tab/tab.tsx
  packages/ui/components/title/title.tsx
  packages/ui/components/wrapper/wrapper.tsx
  turbo.json
Labels: ✨ feature, ❗️ .env changes

#86 feat: Account 페이지 작성글 삭제 기능
  apps/web/src/components/account/accountCategory/accountCategory.tsx
  apps/web/src/components/common/posting/posting.tsx
  apps/web/src/components/layout/accountLayout.tsx
  apps/web/src/components/layout/layout.styled.ts
  apps/web/src/constants/account.ts
  apps/web/src/hooks/mutations/community/useRemoveCommunityPost.ts
  apps/web/src/pages/account/[sub]/index.tsx
  packages/ui/components/container/container.tsx
Labels: ✨ feature

#87 feat: Account 페이지 프로필 모바일 뷰 적용
  apps/web/src/components/account/accountCategory/accountCategory.tsx
  apps/web/src/components/account/profile/profile.styled.ts
  apps/web/src/components/account/profile/profile.tsx
  apps/web/src/components/account/profile/profileInfo.tsx
  apps/web/src/components/common/posting/postingBody.tsx
  packages/ui/components/alert/alert.tsx
Labels: ✨ feature

#88 Feature/market responsive
  apps/web/src/components/common/select/select.tsx
  apps/web/src/components/market/marketFilter/marketFilter.tsx
  apps/web/src/components/market/marketRow/marketRow.tsx
  apps/web/src/components/market/marketSelect/marketSelect.tsx
  apps/web/src/hooks/useSearchKeyword.ts
  apps/web/src/pages/market/index.tsx
  packages/ui/components/table/table.tsx
Labels: 🐛 bug, ✨ feature

#94 fix: 1차 QA 리스트업 피드백 (매거진)
  apps/web/src/components/common/modal/counselingModal.tsx
  apps/web/src/components/common/modal/index.ts
  apps/web/src/components/common/modal/modal.tsx
  apps/web/src/components/common/posting/posting.tsx
  apps/web/src/components/magazine/magazineBanner/magazineBanner.tsx
  apps/web/src/components/magazine/magazineDealer/magazineDealer.tsx
  apps/web/src/components/magazine/magazineList/magazineCard.tsx
  apps/web/src/hooks/mutations/magazine/useMagazineCounseling.ts
  apps/web/src/hooks/queries/useMagazine.ts
  apps/web/src/hooks/queries/useMagazinePost.ts
  apps/web/src/pages/api/magazine/[id].ts
  apps/web/src/pages/api/magazine/counseling.ts
  apps/web/src/pages/community/[subject]/[category]/[id]/index.tsx
  apps/web/src/pages/magazine/[id].tsx
  apps/web/src/pages/search.tsx
  apps/web/src/utils/api/magazine.ts
  packages/types/magazine.d.ts
Labels: 🐛 bug, ❗️ changes requested

#95 fix: 1차 QA 리스트업 피드백 (기타)
  apps/web/src/components/auth/findForm/findForm.tsx
  apps/web/src/components/common/comment/comment.styled.ts
  apps/web/src/components/common/posting/posting.tsx
  apps/web/src/components/layout/header/header.tsx
  apps/web/src/components/layout/navbar/navbar.tsx
  apps/web/src/components/layout/navbar/navbarItem.tsx
  apps/web/src/pages/community/[subject]/[category]/[id]/index.tsx
Labels: 🐛 bug, ❗️ changes requested

#97 fix: 1차 QA 리스트업 피드백 (문의)
  apps/web/next.config.js
  apps/web/src/components/inquiry/advertisementForm/advertisementForm.tsx
  apps/web/src/components/inquiry/dealerForm/dealerForm.tsx
  apps/web/src/components/inquiry/inquiryNavbar/inquiryNavbar.tsx
  apps/web/src/components/inquiry/miscForm/miscForm.tsx
  apps/web/src/components/inquiry/partnershipForm/partnershipForm.tsx
  apps/web/src/components/inquiry/saleForm/saleForm.tsx
  apps/web/src/constants/inquiry.ts
  apps/web/src/middleware.ts
  apps/web/src/pages/account/[sub]/index.tsx
  apps/web/src/pages/inquiry/advertisement.tsx
  apps/web/src/pages/inquiry/dealer.tsx
  apps/web/src/pages/inquiry/index.tsx
  apps/web/src/pages/inquiry/market.tsx
  apps/web/src/pages/inquiry/partnership.tsx
  apps/web/src/utils/api/home.ts
  packages/lib/embeds/error.ts
  packages/ui/form/form.styled.ts
  packages/ui/form/formAgreement.tsx
  packages/ui/form/formAttachment.tsx
  packages/ui/form/formFiles.tsx
  packages/ui/form/formImages.tsx
  packages/ui/form/formRadio.tsx
Labels: 🐛 bug, ❗️ changes requested

#98 refactor: Home/Magazine/Community Server-Side function -> Client-Side Api 교체
  apps/web/src/components/common/comment/comment.tsx
  apps/web/src/components/common/comment/commentArea.tsx
  apps/web/src/components/common/comment/commentBody.tsx
  apps/web/src/components/common/posting/postingBody.tsx
  apps/web/src/components/community/communityCard/communityCard.tsx
  apps/web/src/components/community/communityNavbar/communityNavbar.tsx
  apps/web/src/components/fallback/loading.tsx
  apps/web/src/components/layout/header/header.tsx
  apps/web/src/components/magazine/magazineBanner/magazineBanner.tsx
  apps/web/src/components/magazine/magazineList/magazineCard.tsx
  apps/web/src/components/magazine/magazineScrape/magazineScrape.tsx
  apps/web/src/components/market/marketCard/marketCard.tsx
  apps/web/src/components/market/marketRow/marketRow.tsx
  apps/web/src/hooks/mutations/comment/useAddComment.ts
  apps/web/src/hooks/mutations/comment/useLikeComment.ts
  apps/web/src/hooks/mutations/comment/useRemoveComment.ts
  apps/web/src/hooks/mutations/comment/useUpdateComment.ts
  apps/web/src/hooks/mutations/magazine/useMagazineScrape.ts
  apps/web/src/hooks/queries/community/useCommunityTemporaryStorage.ts
  apps/web/src/hooks/queries/useBase64.ts
  apps/web/src/hooks/queries/useComment.ts
  apps/web/src/hooks/queries/useHome.ts
  apps/web/src/hooks/queries/useMagazine.ts
  apps/web/src/hooks/useInterval.ts
  apps/web/src/hooks/useMarketUrlQuery.ts
  apps/web/src/hooks/useMedia.ts
  apps/web/src/hooks/useMediaQuery.ts
  apps/web/src/hooks/useUrlQuery.ts
  apps/web/src/pages/api/account/category.ts
  apps/web/src/pages/api/account/info.ts
  apps/web/src/pages/api/account/update.ts
  apps/web/src/pages/api/comment/[id].ts
  apps/web/src/pages/api/comment/create.ts
  apps/web/src/pages/api/comment/like.ts
  apps/web/src/pages/api/comment/remove.ts
  apps/web/src/pages/api/comment/update.ts
  apps/web/src/pages/api/home.ts
  apps/web/src/pages/api/magazine/index.ts
  apps/web/src/pages/api/magazine/scrape.ts
  apps/web/src/pages/index.tsx
  apps/web/src/pages/magazine/[id].tsx
  apps/web/src/utils/api/account.ts
  apps/web/src/utils/api/comment.ts
  apps/web/src/utils/api/home.ts
  apps/web/src/utils/api/magazine.ts
Labels: ⛏refactoring

#101 chore: lib 패키지 Fetcher로 교체 & 매거진 스크랩 API 프리페칭 버그 수정
  apps/web/src/components/account/accountCategory/accountCategory.tsx
  apps/web/src/components/magazine/magazineBanner/magazineBanner.tsx
  apps/web/src/components/magazine/magazineList/magazineCard.tsx
  apps/web/src/hooks/mutations/comment/useUpdateComment.ts
  apps/web/src/hooks/mutations/magazine/useMagazineScrape.ts
  apps/web/src/hooks/queries/community/useCommunityBest.ts
  apps/web/src/hooks/queries/useAccount.ts
  apps/web/src/hooks/queries/useAccountCategory.ts
  apps/web/src/hooks/queries/useMarket.ts
  apps/web/src/hooks/queries/useSearch.ts
  apps/web/src/hooks/queries/useUpdateInfo.ts
  apps/web/src/pages/api/auth/phone/confirm-auth.ts
  apps/web/src/pages/api/auth/phone/register-phone.ts
  apps/web/src/pages/api/auth/phone/request-auth.ts
  apps/web/src/pages/index.tsx
  apps/web/src/pages/magazine/[id].tsx
  apps/web/src/utils/api/auth/phone.ts
  apps/web/src/utils/api/auth/token.ts
  apps/web/src/utils/api/auth/user.ts
  apps/web/src/utils/api/market.ts
  apps/web/src/utils/api/market/detail.ts
  apps/web/src/utils/api/partnership.ts
  packages/ui/components/table/table.tsx
Labels: 🐛 bug, ⛏refactoring

#96 fix: 1차 QA 리스트업 피드백 (마켓)
  apps/web/src/components/common/select/select.tsx
  apps/web/src/components/fallback/loading.tsx
  apps/web/src/components/market/marketBanner/marketBanner.tsx
  apps/web/src/components/market/marketContents/marketContents.tsx
  apps/web/src/components/market/marketDetail/components/marketDetailAttached/marketDetailAttached.styled.ts
  apps/web/src/components/market/marketDetail/components/marketDetailCar/marketDetailCar.styled.ts
  apps/web/src/components/market/marketDetail/components/marketDetailCarousel/marketDetailCarousel.styled.ts
  apps/web/src/components/market/marketDetail/components/marketDetailCarousel/marketDetailCarousel.tsx
  apps/web/src/components/market/marketDetail/components/marketDetailDealer/marketDetailDealer.styled.ts
  apps/web/src/components/market/marketDetail/components/marketDetailDealer/marketDetailDealer.tsx
  apps/web/src/components/market/marketDetail/components/marketDetailHeader/marketDetailHeader.styled.ts
  apps/web/src/components/market/marketDetail/components/marketDetailHeader/marketDetailHeader.tsx
  apps/web/src/components/market/marketDetail/components/marketDetailIntroduction/marketDetailIntroduction.styled.ts
  apps/web/src/components/market/marketDetail/components/marketLike/marketLike.tsx
  apps/web/src/components/market/marketDetail/components/marketMine/index.ts
  apps/web/src/components/market/marketDetail/components/marketMine/marketMine.tsx
  apps/web/src/components/market/marketDetail/marketDetail.tsx
  apps/web/src/components/market/marketFilter/marketFilter.tsx
  apps/web/src/components/market/marketRow/marketRow.tsx
  apps/web/src/components/market/marketSelect/marketSelect.tsx
  apps/web/src/constants/market.ts
  apps/web/src/hooks/mutations/market/useChangeSellStatus.ts
  apps/web/src/hooks/mutations/market/useRemoveMarketById.ts
  apps/web/src/pages/market/[category]/[id].tsx
  apps/web/src/pages/partnership/index.tsx
  apps/web/src/utils/api/market.ts
  apps/web/src/utils/market/marketFilter.ts
  apps/web/src/utils/market/marketQuery.ts
  apps/web/tsconfig.json
  packages/types/market.d.ts
Labels: 🐛 bug, ❗️ changes requested

#102 feature: 제휴업체 페이지 반응형 적용
  apps/web/src/components/common/carousel/carousel.styled.ts
  apps/web/src/components/common/carousel/carousel.tsx
  apps/web/src/components/fallback/loading.tsx
  apps/web/src/components/market/marketContents/marketContents.tsx
  apps/web/src/components/partnership/partnershipCard/partnershipCard.tsx
  apps/web/src/components/partnership/partnershipCategory/index.ts
  apps/web/src/components/partnership/partnershipCategory/partnershipCategory.tsx
  apps/web/src/components/partnership/partnershipContents/partnershipContents.tsx
  apps/web/src/components/partnership/partnershipDetail/partnershipDetail.tsx
  apps/web/src/components/partnership/partnershipDetailCard/partnershipDetailCard.tsx
  apps/web/src/components/partnership/partnershipIntroduction/partnershipIntroduction.tsx
  apps/web/src/components/partnership/partnershipList/partnershipList.tsx
  apps/web/src/pages/market/[category]/[id].tsx
  apps/web/src/pages/partnership/[category]/[id].tsx
  apps/web/src/pages/partnership/index.tsx
  apps/web/src/utils/api/partnership.ts
  packages/types/partnership.d.ts
  packages/ui/tsconfig.json
Labels: ✨ feature

#106 feat(web): Advertisment Component Ui 구현
  apps/web/src/components/common/advertisement/advertisement.tsx
  apps/web/src/components/common/advertisement/index.ts
  apps/web/src/pages/community/[subject]/[category]/[id]/index.tsx
  apps/web/src/pages/community/[subject]/[category]/[id]/update.tsx
  apps/web/src/pages/community/[subject]/index.tsx
  apps/web/src/pages/community/create.tsx
  apps/web/src/pages/index.tsx
  apps/web/src/pages/inquiry/index.tsx
  apps/web/src/pages/magazine/[id].tsx
  apps/web/src/pages/magazine/index.tsx
  apps/web/src/pages/market/[category]/[id].tsx
  apps/web/src/pages/market/index.tsx
  apps/web/src/pages/partnership/[category]/[id].tsx
  apps/web/src/pages/partnership/index.tsx
Labels: ✨ feature

#107 fix(web): partnership comment kind 수정
  apps/web/src/components/partnership/partnershipDetail/partnershipDetail.tsx
Labels: 🐛 bug

#112 refactor(web): 마켓/제휴 Api 관심사 분리
  apps/web/src/components/market/marketContents/marketContents.tsx
  apps/web/src/components/market/marketDetail/components/marketLike/marketLike.tsx
  apps/web/src/components/market/marketDetail/components/marketMine/marketMine.tsx
  apps/web/src/components/market/marketList/marketList.tsx
  apps/web/src/components/partnership/partnershipCard/partnershipCard.tsx
  apps/web/src/components/partnership/partnershipDetail/partnershipDetail.tsx
  apps/web/src/components/partnership/partnershipList/partnershipList.tsx
  apps/web/src/constants/queries.ts
  apps/web/src/hooks/queries/useMarket.ts
  apps/web/src/hooks/queries/useMarketDetail.ts
  apps/web/src/hooks/queries/usePartnership.ts
  apps/web/src/hooks/queries/usePartnershipDetail.ts
  apps/web/src/hooks/queries/useSearch.ts
  apps/web/src/pages/api/market.ts
  apps/web/src/pages/api/market/[id].ts
  apps/web/src/pages/api/partnership/index.ts
  apps/web/src/pages/market/[category]/[id].tsx
  apps/web/src/pages/market/index.tsx
  apps/web/src/pages/partnership/[category]/[id].tsx
  apps/web/src/pages/partnership/index.tsx
  apps/web/src/utils/api/market.ts
  apps/web/src/utils/api/market/apis.ts
  apps/web/src/utils/api/market/detail.ts
  apps/web/src/utils/api/market/index.ts
  apps/web/src/utils/api/market/keys.ts
  apps/web/src/utils/api/market/mutations.ts
  apps/web/src/utils/api/market/queries.ts
  apps/web/src/utils/api/partnership.ts
  apps/web/src/utils/api/partnership/apis.ts
  apps/web/src/utils/api/partnership/index.ts
  apps/web/src/utils/api/partnership/keys.ts
  apps/web/src/utils/api/partnership/queries.ts
  packages/lib/formatter.ts
Labels: ✨ feature

#111 fix(web): 2차 QA 리스트업 피드백 (제휴업체)
  apps/web/src/components/common/carousel/carousel.styled.ts
  apps/web/src/components/common/carousel/carousel.tsx
  apps/web/src/components/fallback/loading.tsx
  apps/web/src/components/partnership/partnershipCard/partnershipCard.tsx
  apps/web/src/components/partnership/partnershipDetail/partnershipDetail.tsx
  apps/web/src/components/partnership/partnershipList/partnershipList.tsx
  apps/web/src/constants/partnership.ts
  apps/web/src/constants/queries.ts
  apps/web/src/pages/partnership/[category]/[id].tsx
  apps/web/src/pages/partnership/index.tsx
  apps/web/src/utils/api/partnership/apis.ts
Labels: ❗️ changes requested

#114 fix(web): 2차 QA 리스트업 피드백 (커뮤니티)
  apps/web/src/components/common/comment/comment.tsx
  apps/web/src/components/common/modal/modal.tsx
  apps/web/src/components/common/posting/posting.tsx
  apps/web/src/components/community/communityBestList/communityBestList.tsx
  apps/web/src/components/community/communityCard/communityCard.tsx
  apps/web/src/components/community/communityForm/communityForm.tsx
  apps/web/src/components/community/communityList/communityList.tsx
  apps/web/src/http/server/community/apis.ts
  apps/web/src/http/server/home/queries.ts
  apps/web/src/pages/community/[subject]/[category]/[id]/index.tsx
  apps/web/src/pages/community/[subject]/[category]/[id]/update.tsx
  apps/web/src/pages/community/[subject]/index.tsx
  apps/web/src/pages/community/create.tsx
  apps/web/src/pages/magazine/[id].tsx
  packages/hooks/index.tsx
  packages/hooks/package.json
  packages/hooks/useDebounce.ts
  packages/hooks/usePreservedCallback .ts
  packages/hooks/usePreservedReference.ts
  packages/lib/checkDeeplyEquall.ts
  packages/lib/index.ts
  packages/tsconfig/base.json
  packages/ui/components/button/button.tsx
  packages/ui/components/pagination/pagination.tsx
  packages/ui/components/tab/tab.tsx
  packages/ui/form/formSelect.tsx
  pnpm-lock.yaml
Labels: 🐛 bug, ❗️ changes requested

#115 fix(web): 2차 QA 리스트업 피드백 (마이페이지)
  apps/web/public/images/create.png
  apps/web/public/images/delete.png
  apps/web/public/svg/create-filled.svg
  apps/web/public/svg/delete.svg
  apps/web/src/components/account/profile/profile.tsx
  apps/web/src/components/common/logo/logo.tsx
  apps/web/src/components/common/posting/posting.tsx
  apps/web/src/components/common/posting/postingBody.tsx
  apps/web/src/components/community/communityCard/communityCard.tsx
  apps/web/src/components/inquiry/inquiryCard/inquiryCard.tsx
  apps/web/src/components/layout/hamburger/hamburger.tsx
  apps/web/src/components/layout/header/header.tsx
  apps/web/src/components/magazine/magazineBanner/magazineBanner.tsx
  apps/web/src/components/magazine/magazineList/magazineCard.tsx
  apps/web/src/components/market/marketCard/marketCard.tsx
  apps/web/src/components/market/marketRow/marketRow.tsx
Labels: 🐛 bug, ❗️ changes requested

#117 fix(web): 2차 QA 리스트업 피드백 (메인/문의)
  apps/web/src/components/account/accountCategory/accountCategory.tsx
  apps/web/src/components/account/accountPasswordForm/accountPasswordForm.tsx
  apps/web/src/components/account/accountUpdateForm/accountUpdateForm.tsx
  apps/web/src/components/auth/signinForm/signinForm.tsx
  apps/web/src/components/auth/signupForm/signupForm.tsx
  apps/web/src/components/common/posting/posting.tsx
  apps/web/src/components/common/posting/postingHead.tsx
  apps/web/src/components/community/communityCard/communityCard.tsx
  apps/web/src/components/inquiry/advertisementForm/advertisementForm.tsx
  apps/web/src/components/inquiry/dealerForm/dealerForm.tsx
  apps/web/src/components/inquiry/inquiryNavbar/inquiryNavbar.tsx
  apps/web/src/components/inquiry/miscForm/miscForm.tsx
  apps/web/src/components/inquiry/partnershipForm/partnershipForm.tsx
  apps/web/src/components/inquiry/saleForm/saleForm.tsx
  apps/web/src/components/magazine/magazineBanner/magazineBanner.tsx
  apps/web/src/components/magazine/magazineList/magazineList.tsx
  apps/web/src/components/search/index.ts
  apps/web/src/components/search/searchAll/searchAll.tsx
  apps/web/src/components/search/searchList/searchList.tsx
  apps/web/src/components/search/searchNavbar/index.ts
  apps/web/src/components/search/searchNavbar/searchNavbar.tsx
  apps/web/src/components/search/searchPartnership/index.ts
  apps/web/src/components/search/searchPartnership/searchPartnership.tsx
  apps/web/src/http/server/magazine/apis.ts
  apps/web/src/http/server/magazine/queries.ts
  apps/web/src/pages/magazine/index.tsx
  apps/web/src/pages/search.tsx
  packages/hooks/package.json
  packages/hooks/useDebounce.ts
  packages/lib/debounce.ts
  packages/lib/index.ts
  packages/lib/package.json
  packages/types/search.d.ts
  packages/ui/components/container/container.tsx
  pnpm-lock.yaml
Labels: 🐛 bug, ❗️ changes requested

#118 refactor(web): Components 폴더 내부 컴포넌트들 파일 구조 변경
  apps/web/src/components/account/accountCategory/accountCategory.tsx
  apps/web/src/components/account/profile/components/index.ts
  apps/web/src/components/account/profile/components/profileBackground.tsx
  apps/web/src/components/account/profile/components/profileInfo.tsx
  apps/web/src/components/account/profile/components/profileRepresentative.tsx
  apps/web/src/components/account/profile/profile.tsx
  apps/web/src/components/common/comment/comment.tsx
  apps/web/src/components/common/comment/components/commentArea.tsx
  apps/web/src/components/common/comment/components/commentBody.tsx
  apps/web/src/components/common/comment/components/commentHead.tsx
  apps/web/src/components/common/comment/components/index.ts
  apps/web/src/components/common/modal/authModal.tsx
  apps/web/src/components/common/modal/index.ts
  apps/web/src/components/common/modal/temporaryStorageModal.tsx
  apps/web/src/components/common/posting/components/index.ts
  apps/web/src/components/common/posting/components/postingBody.tsx
  apps/web/src/components/common/posting/components/postingHead.tsx
  apps/web/src/components/common/posting/posting.tsx
  apps/web/src/components/home/magazine/magazine.tsx
  apps/web/src/components/inquiry/index.ts
  apps/web/src/components/inquiry/inquiryCard/index.ts
  apps/web/src/components/magazine/index.ts
  apps/web/src/components/magazine/magazineCard/index.ts
  apps/web/src/components/magazine/magazineCard/magazineCard.tsx
  apps/web/src/components/magazine/magazineList/magazineList.tsx
  apps/web/src/components/search/searchAll/searchAll.tsx
  apps/web/src/components/search/searchMagazine/searchMagazine.tsx
  apps/web/src/pages/account/[sub]/index.tsx
Labels: ⛏refactoring

#124 refactror(web,lib): Api Fetch Wrapper 리팩토링
  apps/web/package.json
  apps/web/src/components/account/accountCategoryList/accountCategoryList.tsx
  apps/web/src/components/account/accountPasswordForm/accountPasswordForm.tsx
  apps/web/src/components/account/accountUpdateForm/accountUpdateForm.tsx
  apps/web/src/components/account/profile/components/profileBackground.tsx
  apps/web/src/components/account/profile/components/profileRepresentative.tsx
  apps/web/src/components/common/comment/components/commentArea.tsx
  apps/web/src/components/common/comment/components/commentBody.tsx
  apps/web/src/components/common/posting/posting.tsx
  apps/web/src/components/community/communityForm/communityForm.tsx
  apps/web/src/components/home/magazine/magazine.tsx
  apps/web/src/components/inquiry/advertisementForm/advertisementForm.tsx
  apps/web/src/components/inquiry/dealerForm/dealerForm.tsx
  apps/web/src/components/inquiry/miscForm/miscForm.tsx
  apps/web/src/components/inquiry/partnershipForm/partnershipForm.tsx
  apps/web/src/components/inquiry/saleForm/saleForm.tsx
  apps/web/src/components/magazine/magazineDealer/magazineDealer.tsx
  apps/web/src/components/magazine/magazineScrape/magazineScrape.tsx
  apps/web/src/components/market/marketDetail/components/marketLike/marketLike.tsx
  apps/web/src/components/market/marketDetail/components/marketMine/marketMine.tsx
  apps/web/src/hooks/queries/useBase64.ts
  apps/web/src/hooks/useAuth.ts
  apps/web/src/http/core/index.ts
  apps/web/src/http/server/account/apis.ts
  apps/web/src/http/server/account/queries.ts
  apps/web/src/http/server/auth/token.ts
  apps/web/src/http/server/auth/user.ts
  apps/web/src/http/server/comment/apis.ts
  apps/web/src/http/server/comment/mutations.ts
  apps/web/src/http/server/community/apis.ts
  apps/web/src/http/server/community/mutations.ts
  apps/web/src/http/server/community/queries.ts
  apps/web/src/http/server/home/apis.ts
  apps/web/src/http/server/magazine/apis.ts
  apps/web/src/http/server/magazine/mutations.ts
  apps/web/src/http/server/market/apis.ts
  apps/web/src/http/server/market/mutations.ts
  apps/web/src/http/server/partnership/apis.ts
  apps/web/src/http/server/search/apis.ts
  apps/web/src/pages/account/[sub]/index.tsx
  apps/web/src/pages/account/[sub]/update.tsx
  apps/web/src/pages/api/auth/[...nextauth].ts
  apps/web/src/pages/api/auth/user/signin.ts
  apps/web/src/pages/community/[subject]/[category]/[id]/update.tsx
  apps/web/src/pages/community/create.tsx
  apps/web/src/pages/inquiry/market.tsx
  packages/lib/api/fetcher.ts
  packages/lib/api/fetcherWrapper.ts
  packages/lib/api/index.ts
  packages/lib/embeds/error.ts
  packages/lib/embeds/httpError.ts
  packages/lib/embeds/index.ts
  packages/lib/index.ts
  packages/lib/isServer.ts
  packages/tsconfig/base.json
  pnpm-lock.yaml
Labels: ⛏refactoring

#125 feat(web): 배너 적용
  apps/web/src/components/home/banner/banner.tsx
  apps/web/src/components/home/banner/index.ts
  apps/web/src/http/server/home/apis.ts
  apps/web/src/http/server/home/keys.ts
  apps/web/src/http/server/home/queries.ts
  apps/web/src/pages/index.tsx
Labels: ✨ feature

#126 fix(web,ui): 새롭게 추가된 2차 QA 리스트업 피드백
  apps/web/src/components/community/communityCard/communityCard.tsx
  apps/web/src/components/community/communityForm/communityForm.tsx
  apps/web/src/components/magazine/magazineList/magazineList.tsx
  packages/ui/components/input/input.tsx
  packages/ui/form/formSelect.tsx
Labels: 🐛 bug, ❗️ changes requested

#127 fix(web): 2차 QA 리스트업 피드백 (마켓)
  apps/web/src/components/common/select/select.styled.ts
  apps/web/src/components/common/select/select.tsx
  apps/web/src/components/home/market/marketBest.tsx
  apps/web/src/components/market/marketCar/marketCar.styled.ts
  apps/web/src/components/market/marketCar/marketCar.tsx
  apps/web/src/components/market/marketCard/marketCard.styled.ts
  apps/web/src/components/market/marketCard/marketCard.tsx
  apps/web/src/components/market/marketContents/marketContents.tsx
  apps/web/src/components/market/marketDetail/components/marketDetailDealer/marketDetailDealer.styled.ts
  apps/web/src/components/market/marketDetail/components/marketDetailDealer/marketDetailDealer.tsx
  apps/web/src/components/market/marketDetail/components/marketMine/marketMine.tsx
  apps/web/src/components/market/marketDetail/marketDetail.tsx
  apps/web/src/components/market/marketFilter/marketFilter.styled.ts
  apps/web/src/components/market/marketFilter/marketFilter.tsx
  apps/web/src/components/market/marketFilter/marketFilterArea/index.ts
  apps/web/src/components/market/marketFilter/marketFilterArea/marketFilterArea.tsx
  apps/web/src/components/market/marketSelect/marketSelect.styled.ts
  apps/web/src/components/market/marketSelect/marketSelect.tsx
  apps/web/src/hooks/useNextQuery.ts
  apps/web/src/http/server/market/apis.ts
  apps/web/src/http/server/market/mutations.ts
  apps/web/src/pages/market/[category]/[id].tsx
  apps/web/src/utils/market/marketQuery.ts
  packages/ui/components/category/category.tsx
Labels: ❗️ changes requested

#129 매물 삭제/판매 완료 기능 추가 및 Wrapper 스타일로 변경, next/router -> next/navigation 변경
  apps/web/src/components/market/marketBanner/marketBanner.styled.ts
  apps/web/src/components/market/marketBanner/marketBanner.tsx
  apps/web/src/components/market/marketCard/marketCard.styled.ts
  apps/web/src/components/market/marketCard/marketCard.tsx
  apps/web/src/components/market/marketDetail/components/index.ts
  apps/web/src/components/market/marketDetail/components/marketDetailAttached/marketDetailAttached.styled.ts
  apps/web/src/components/market/marketDetail/components/marketDetailAttached/marketDetailAttached.tsx
  apps/web/src/components/market/marketDetail/components/marketDetailCar/marketDetailCar.styled.ts
  apps/web/src/components/market/marketDetail/components/marketDetailCar/marketDetailCar.tsx
  apps/web/src/components/market/marketDetail/components/marketDetailHeader/marketDetailHeader.styled.ts
  apps/web/src/components/market/marketDetail/components/marketDetailHeader/marketDetailHeader.tsx
  apps/web/src/components/market/marketDetail/components/marketDetailIntroduction/marketDetailIntroduction.styled.ts
  apps/web/src/components/market/marketDetail/components/marketDetailIntroduction/marketDetailIntroduction.tsx
  apps/web/src/components/market/marketDetail/components/marketLike/index.ts
  apps/web/src/components/market/marketDetail/components/marketLike/marketLike.tsx
  apps/web/src/components/market/marketDetail/components/marketMine/index.ts
  apps/web/src/components/market/marketDetail/components/marketMine/marketMine.tsx
  apps/web/src/components/market/marketDetail/marketDetail.tsx
  apps/web/src/components/market/marketFilter/marketFilter.styled.ts
  apps/web/src/components/market/marketFilter/marketFilter.tsx
  apps/web/src/components/market/marketRow/marketRow.tsx
  apps/web/src/components/partnership/banner/banner.styled.ts
  apps/web/src/components/partnership/banner/banner.tsx
  apps/web/src/components/partnership/partnershipCategory/partnershipCategory.tsx
  apps/web/src/hooks/useSearchKeyword.ts
  apps/web/src/http/server/market/apis.ts
  apps/web/src/http/server/market/mutations.ts
  apps/web/src/pages/market/[category]/[id].tsx
  packages/lib/formatter.ts
Labels: ❗️ changes requested
